### ISSUE TITLE
Gitsigns no longer works in dotfiles (yadm) Git Repo

### ISSUE THREAD

**Issue by Necrom4** [lewis6991/gitsigns.nvim#1315]
### Description

Since the commit [2ac55dbde63eec1a41c65e6574a8ddef6d816262](https://github.com/lewis6991/gitsigns.nvim/commit/2ac55dbde63eec1a41c65e6574a8ddef6d816262), I no longer am able to use Gitsigns with my dotfiles (such as `.zshrc` or `~/.config/nvim/lua/plugins/gitsigns.lua`).

This problem occurs when I do `nvim <filename>` or even when I open it from my picker's most recent files selection. Weirdly enough, the problem does not occur if I open the file from Lazygit.

The problem itself consits of Diff column signs not appearing, nor the keymaps. The `:Gitsigns` command is still available but does nothing. These "symptoms" are very similar to when I open a config file while in another Git Repo, in which case I usually change `vim.fn.GIT_DIR` to the Yadm Repo, or edit from `~/`.

### Neovim version

v0.11.1

### Operating system and version

Ubuntu 24.04.2 LTS (WSL2)

### Expected behavior

Gitsigns should be available while editing config files from home or their own directory, just as it used to work before [2ac55dbde63eec1a41c65e6574a8ddef6d816262](https://github.com/lewis6991/gitsigns.nvim/commit/2ac55dbde63eec1a41c65e6574a8ddef6d816262)

### Actual behavior

Diff signs column and Gitsigns keymaps are not available. `:Gitsigns <arg>` command is but doesn't do anything.

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. Paste above config in your `init.lua`
2. Open any file tracked by your dotfiles repository (e.g. `~/.config/nvim/lua/plugins/gitsigns.lua`)
3. Remove a character
4. Diff column signs doesn't appear/change

### Gitsigns debug messages

```text
121.69 D git: git --git-dir $CWD/.local/share/yadm/repo.git --work-tree $CWD/.local/share/yadm rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
124.00 D get_info: '~/.config/nvim/lua/plugins' is outside worktree '~/.local/share/yadm'
124.04 D new: Not in git repo
124.08 D attach(5): Empty git obj
9749.84 D cli.run: Running action 'debug_messages' with arguments {}
72860.98 D cli.run: Running action 'debug_messages' with arguments {}
```

### Gitsigns cache

```lua

```

**Comment by eshepelyuk** [comment]
There's dedicated companion plugin for yadm support - and it works well with the latest versions of gitsigns.nvim
https://github.com/purarue/gitsigns-yadm.nvim

**Comment by Necrom4** [comment]
> There's dedicated companion plugin for yadm support - and it works well with the latest versions of gitsigns.nvim https://github.com/purarue/gitsigns-yadm.nvim

That's pretty cool! But unfortunately it doesn't solve the problem I have, it still won't work unless I set the commit to the last one that worked. (PS: I already had a lua function that did what this plugin does, so it'll be cool to use this instead, it'll be cleaner. Thx!)

**Comment by eshepelyuk** [comment]
> > There's dedicated companion plugin for yadm support - and it works well with the latest versions of gitsigns.nvim https://github.com/purarue/gitsigns-yadm.nvim
> 
> That's pretty cool! But unfortunately it doesn't solve the problem I have, it still won't work unless I set the commit to the last one that worked. (PS: I already had a lua function that did what this plugin does, so it'll be cool to use this instead, it'll be cleaner. Thx!)

i've updated plugin few minutes before posting this, it's working for me with the latest gitsigns.nvim commit.

**Comment by lewis6991** [comment]
> > There's dedicated companion plugin for yadm support - and it works well with the latest versions of gitsigns.nvim https://github.com/purarue/gitsigns-yadm.nvim
> 
> That's pretty cool! But unfortunately it doesn't solve the problem I have, it still won't work unless I set the commit to the last one that worked. (PS: I already had a lua function that did what this plugin does, so it'll be cool to use this instead, it'll be cleaner. Thx!)

Why didn't you include that in the issue report.

**Comment by Necrom4** [comment]
> i've updated plugin few minutes before posting this, it's working for me with the latest gitsigns.nvim commit.

Unfortunately the latest commit I have access to is still from 3 months ago so it still won't work for me :/

**Comment by Necrom4** [comment]
> Why didn't you include that in the issue report.

Sorry about that, I completely forgot about it's existence as it works in the background without me even noticing. But then again it isn't what's causing the problem, as Gitsigns was working as of 2 commits ago.

**Comment by lewis6991** [comment]
Simply reporting that something isn't working is not an adequate issue report. The issue template must be followed so I can apply my time productively to this project.

Your reproduction steps are not complete and are not usable.

Is there anything in the issue template you did not understand?

**Comment by Necrom4** [comment]
No, not at all, your template is fine. I did have trouble understanding how to convey my understanding of the problem but that's because this is one of the very few times I've ever created an issue.

Anyway seems like my yadm function was indeed what was causing problems, and using gitsigns-yadm solves it. Now I just gotta change every yadm-related keymap so they work again, but that's another story.

Thanks again to you two!
