### ISSUE TITLE
Assertion failed in coroutine

### ISSUE THREAD

**Issue by scallaway** [lewis6991/gitsigns.nvim#847]
### Description

This is very similar to https://github.com/lewis6991/gitsigns.nvim/issues/814, but happening in a slightly different part of `hunks.lua`.

I can't work out quite _when_ this crash happens, but I've found it to happen pretty consistently in a Python file that is open for a minute or so. Of course when the error shows, the git signs completely vanish.

---

I had a run through the `hunks.lua` file and found the `assert` thats failing. I commented it out and had a play around with the minimum config again and that seems to do the job, but I can't be sure that's not _absolutely_ required in the plugin.

### Neovim version

nightly

### Operating system and version

debian

### Actual behavior

Error output is the following;
```
Error executing vim.schedule lua callback: ...gitsigns_issue/gitsigns//lua/gitsigns/async.lua:76: The coroutine failed with this message: ...gitsigns_issue/gitsigns//lua/gitsigns/hunks.lua:172: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...gitsigns_issue/gitsigns//lua/gitsigns/hunks.lua:172: in function 'calc_signs'
        ...gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:59: in function 'apply_win_signs0'
        ...gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:81: in function 'apply_win_signs'
        ...gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:454: in function 'fn'
        ...tform/gitsigns_issue/gitsigns//lua/gitsigns/debounce.lua:76: in function 'update'
        ...gitsigns_issue/gitsigns//lua/gitsigns/watcher.lua:88: in function <...gitsigns_issue/gitsigns//lua/gitsigns/watcher.lua:59>
stack traceback:
        [C]: in function 'error'
        ...gitsigns_issue/gitsigns//lua/gitsigns/async.lua:76: in function 'cb'
        ...gitsigns_issue/gitsigns//lua/gitsigns/async.lua:113: in function 'cb'
        ...gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:36: in function <...gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:34>
```

### Minimal config

```Lua
for name, url in pairs({
	gitsigns = "https://github.com/lewis6991/gitsigns.nvim",
	-- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
	nvim_lspconfig = "https://github.com/neovim/nvim-lspconfig",
}) do
	local install_path = vim.fn.fnamemodify("gitsigns_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

require("gitsigns").setup({
	debug_mode = true, -- You must add this to enable debug messages
	-- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
})

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE

require("lspconfig").pyright.setup({})
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Wait for a little bit

**Comment by lewis6991** [comment]
I improved the assertion message in 61e50f37ec3c1d739963197b9ce5e16fb7141cf7. Can you report the message when it happens again.

**Comment by scallaway** [comment]
```
Error executing vim.schedule lua callback: ...platform/gitsigns_issue/gitsigns//lua/gitsigns/async.lua:76: The coroutine failed with this message: ...platform/gitsigns_issue/gitsigns//lua/gitsigns/hunks.lua:172: Invalid hunk with untracked=true hunk="@@ -2308,1 +2308,3 @@"

stack traceback:
        [C]: in function 'assert'
        ...platform/gitsigns_issue/gitsigns//lua/gitsigns/hunks.lua:172: in function 'calc_signs'
        ...atform/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:59: in function 'apply_win_signs0'
        ...atform/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:81: in function 'apply_win_signs'
        ...atform/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:454: in function 'fn'
        ...tform/gitsigns_issue/gitsigns//lua/gitsigns/debounce.lua:76: in function 'update'
        ...atform/gitsigns_issue/gitsigns//lua/gitsigns/watcher.lua:88: in function <...atform/gitsigns_issue/gitsigns//lua/gitsigns/watcher.lua:59>
stack traceback:
        [C]: in function 'error'
        ...platform/gitsigns_issue/gitsigns//lua/gitsigns/async.lua:76: in function 'cb'
        ...platform/gitsigns_issue/gitsigns//lua/gitsigns/async.lua:113: in function 'cb'
        ...atform/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:36: in function <...atform/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:34>
Error in decoration provider gitsigns.win:
Error executing lua: ...platform/gitsigns_issue/gitsigns//lua/gitsigns/hunks.lua:172: Invalid hunk with untracked=true hunk="@@ -2308,1 +2308,3 @@"
stack traceback:
        [C]: in function 'assert'
        ...platform/gitsigns_issue/gitsigns//lua/gitsigns/hunks.lua:172: in function 'calc_signs'
        ...atform/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:63: in function 'apply_win_signs0'
        ...atform/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:81: in function 'apply_win_signs'
        ...atform/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:511: in function <...atform/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:502>
```

That's what I get on the latest version of gitsigns

**Comment by scallaway** [comment]
For what it's worth, that's editing the same file that I was recreating the issue on earlier. It's a file that already exists in source control and I've just updated some lines (edited a few, added a few).

The line 2308 that it's outputting there is a line that I've edited.

**Comment by lewis6991** [comment]
Gitsigns doesn't think this file is maintained in git for whatever reason (due to `untracked=true`).

This will come from when Gitsigns run `git ls-files <filename>` and then determines whether the file is tracked based on the result.

**Comment by alligatortower** [comment]
From casual observation this error seems to happen to me when switching out of (or perhaps back to) the tmux tab where I'm running neovim. If it's the result of something I'm doing while tabbed away, I haven't noticed a pattern. It's extremely intermittent in all cases.

**Comment by mosheavni** [comment]
happens to me frequently as well

**Comment by astutecat** [comment]
I tend to see this issue happen when I do some git-related calls outside of nvim in another tmux window - for example reverting changes or some other index-based operations.

If you use [stacked git](https://github.com/stacked-git/stgit), it appears to happen a lot if you use it to insert changes into another commit -- this operation presumably involves rapidly stashing/reverting and re-applying of changes.

**Comment by scallaway** [comment]
> I tend to see this issue happen when I do some git-related calls outside of nvim in another tmux window

This is interesting.

I _do_ use Lazygit in another tmux window, so that might be affecting it.

I'm going to run a temporary branch (https://github.com/scallaway/gitsigns.nvim/tree/temp-fix-assertion) for a while to see if anything else badly breaks. Given as far as I can tell that's the line that is complaining the entire time.

**Comment by astutecat** [comment]
using lazygit and doing reverts, stashes ... something like that where the index changes seems to trigger it. Some kind of 'rug-pull' where the file goes from being in a modified state to not?

**Comment by lewis6991** [comment]
I just want to point out no one has yet to provide the output of debug messages when this error occurs. The debug messages should indicate what commands for each buffer is being issued as well whenever the gitdir watcher triggers.

**Comment by lewis6991** [comment]
I don't know if this will fix the issue but #869 should fix some related problems around certain kinds of 'rug-pulls'.

**Comment by mshakaE** [comment]
@lewis6991
I am having kind of the same issue every time i leave my terminal and come back to it i get this error 

`Error executing vim.schedule lua callback: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:76: The coroutine failed with this message: vim/shared.lua:0: Expected table, got nil
stack traceback:
        [C]: in function 'assert'
        vim/shared.lua: in function 'tbl_isempty'
        ...ack/packer/start/gitsigns.nvim/lua/gitsigns/diff_int.lua:72: in function 'run_diff'
        ...pack/packer/start/gitsigns.nvim/lua/gitsigns/manager.lua:424: in function 'fn'
        ...ack/packer/start/gitsigns.nvim/lua/gitsigns/debounce.lua:76: in function 'update'
        ...pack/packer/start/gitsigns.nvim/lua/gitsigns/watcher.lua:88: in function <...pack/packer/start/gitsigns.nvim/lua/gitsigns/watcher.lua:59>
stack traceback:
        [C]: in function 'error'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:76: in function 'cb'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:113: in function 'cb'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:186: in function <...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:184>`
      
I use lazygit as well in my other tmux window
usually I re open my nvim again and all the signs are back normally with no errors

**Comment by scallaway** [comment]
> I just want to point out no one has yet to provide the output of debug messages when this error occurs.

I've just pulled the following logs out now that I've been able to see it happen a few times. Note that file names are redacted.

```
-- Console error --
Error executing vim.schedule lua callback: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:76: The coroutine failed with this message: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/hunks.lua:172: Invalid hunk with untracked=true hunk="@@ -16,1 +16,1 @@"
stack traceback:
        [C]: in function 'assert'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/hunks.lua:172: in function 'calc_signs'
        ...pack/packer/start/gitsigns.nvim/lua/gitsigns/manager.lua:50: in function 'apply_win_signs0'
        ...pack/packer/start/gitsigns.nvim/lua/gitsigns/manager.lua:72: in function 'apply_win_signs'
        ...pack/packer/start/gitsigns.nvim/lua/gitsigns/manager.lua:445: in function 'fn'
        ...ack/packer/start/gitsigns.nvim/lua/gitsigns/debounce.lua:76: in function 'update'
        ...pack/packer/start/gitsigns.nvim/lua/gitsigns/watcher.lua:103: in function <...pack/packer/start/gitsigns.nvim/lua/gitsigns/watcher.lua:77>
stack traceback:
        [C]: in function 'error'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:76: in function 'cb'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:113: in function 'cb'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:186: in function <...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:184>
Press ENTER or type command to continue

-- Debug messages --

cli.run: Running action 'debug_messages' with arguments {}
watcher_cb(1): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(72): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(74): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(93): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(96): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(30): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(198): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(44): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(201): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(217): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(255): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(1): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(72): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(74): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(93): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(96): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(198): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(44): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(201): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(217): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(255): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(1): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(72): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(74): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(93): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(96): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(30): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(198): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(44): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(201): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(217): Git dir update: 'FETCH_HEAD' { change = true }
watcher_cb(255): Git dir update: 'FETCH_HEAD' { change = true }
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.ts
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.ts
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.ts
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol working_dir/*.py

run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git show :0:*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git show :0:*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git show :0:*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git show :0:*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git show :0:*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git show :0:*.ts
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git show :0:*.ts
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git show :0:*.ts
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git show :0:*.tsx
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir working_dir.git show :0:*.py
update(1): updates: 3746, jobs: 5644
update(72): updates: 3747, jobs: 5644
update(74): updates: 3748, jobs: 5644
update(93): updates: 3749, jobs: 5644
update(96): updates: 3750, jobs: 5644
update(198): updates: 3751, jobs: 5644
update(44): updates: 3752, jobs: 5644
update(201): updates: 3753, jobs: 5644
update(217): updates: 3754, jobs: 5644
update(255): updates: 3755, jobs: 5644
cli.run: Running action 'dump_cache' with arguments {}
cli.run: Running action 'debug_messages' with arguments {}
```

For context, this _only_ seems to happen in the pane that contains a Python file. I had two vertical panes setup, one with a JSX file and one with a Python file. I can't remember which one was focused (as I was tabbed out).

**Comment by lewis6991** [comment]
Redacting all filenames to `*` makes it difficult to see what jobs are running on each file. I can only assume that every file in this log is getting:

```
git rev-parse ... HEAD
git ls-files ... <file>
git show :0:<file>
```

My only guess is that the information of `rev-parse` is stale by the time `git show` is run.

**Comment by lewis6991** [comment]
I've updated #869 with some changes to how the watcher is debounced.

If anyone sees this issue **with this PR applied**, then please report the debug messages.

Please refrain from any further "me too!" comments.

**Comment by lewis6991** [comment]
Any issues yet?

**Comment by scallaway** [comment]
I keep meaning to come back to this - I just haven't had time this week.

I am still seeing issues (and can see you merged the PR into the base branch) but I want to try and find another good recreation to get you the info that you require

**Comment by scallaway** [comment]
Does this help?

```
update(28): updates: 1686, jobs: 79
update(1): updates: 1687, jobs: 79
update(322): updates: 1688, jobs: 79
update(323): updates: 1689, jobs: 79
update(324): updates: 1690, jobs: 79
watcher_cb(1): Git dir update: '.gitstatus.KLajmI' { rename = true }
watcher_cb(28): Git dir update: '.gitstatus.KLajmI' { rename = true }
watcher_cb(322): Git dir update: '.gitstatus.KLajmI' { rename = true }
watcher_cb(323): Git dir update: '.gitstatus.KLajmI' { rename = true }
watcher_cb(324): Git dir update: '.gitstatus.KLajmI' { rename = true }
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /home/s
callaway/dev/work/work_repo/dir_a/tests/test.py
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /home/s
callaway/dev/work/work_repo/dir_a/store.py
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /home/s
callaway/dev/work/work_repo/dir_b/trigger/store.py
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /home/s
callaway/dev/work/work_repo/dir_b/tests/strategies.py
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git diff --name-status -C --cached
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /home/s
callaway/dev/work/work_repo/dir_a/user_model.py
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git diff --name-status -C --cached
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git show :0:dir_a/store.py
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git show :0:dir_a/tests/test_actions.py
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git show :0:dir_b/trigger/tests/strategies.py
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git show :0:dir_b/trigger/store.py
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir /home/scallaway/dev/work/work_repo/.git show :0:dir_a/user_model.py
update(1): updates: 1691, jobs: 96
update(322): updates: 1692, jobs: 96
update(28): updates: 1693, jobs: 96
update(323): updates: 1694, jobs: 96
update(324): updates: 1695, jobs: 96
cli.run: Running action 'debug_messages' with arguments {}
```

**Comment by lewis6991** [comment]
What was the error?

**Comment by scallaway** [comment]
@lewis6991 
> What was the error?

```
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:76: The coroutine│
 failed with this message: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:172: Invalid hunk with untracked=│
true hunk="@@ -33,1 +33 @@"                                                                                             │
stack traceback:                                                                                                        │
        [C]: in function 'assert'                                                                                       │
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:172: in function 'calc_signs'                       │
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:53: in function 'apply_win_signs0'                  │
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:72: in function 'apply_win_signs'                   │
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:502: in function 'fn'                               │
        .../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/debounce.lua:68: in function 'update'                            │
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua:92: in function <...l/share/nvim/lazy/gitsigns.nvim/│
lua/gitsigns/watcher.lua:65>                                                                                            │
stack traceback:                                                                                                        │
        [C]: in function 'error'                                                                                        │
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:76: in function 'cb'                                │
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:113: in function 'cb'                               │
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:448: in function <...l/share/nvim/lazy/gitsigns.nvim│
/lua/gitsigns/manager.lua:433> 
```

Managed to capture it just as it happened, this is what I see

Although this still isn't truly reproducable. Takes ages to find the error as I'm not _always_ working with Python either

**Comment by Nadrieril** [comment]
I pretty consistently get this error when I do complicated rebases then come back to my editor. Just got one:
```
Error executing vim.schedule lua callback: ...eovimPackages/start/gitsigns.nvim/lua/gitsigns/async.lua:105: The coroutine failed with this message: ...eovimPackages/start/gitsigns.nvim/lua/gitsign
s/hunks.lua:190: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...eovimPackages/start/gitsigns.nvim/lua/gitsigns/hunks.lua:190: in function 'calc_signs'
        ...vimPackages/start/gitsigns.nvim/lua/gitsigns/manager.lua:64: in function 'apply_win_signs0'
        ...vimPackages/start/gitsigns.nvim/lua/gitsigns/manager.lua:81: in function 'apply_win_signs'
        ...vimPackages/start/gitsigns.nvim/lua/gitsigns/manager.lua:413: in function 'fn'
        ...imPackages/start/gitsigns.nvim/lua/gitsigns/debounce.lua:80: in function 'update'
        ...vimPackages/start/gitsigns.nvim/lua/gitsigns/manager.lua:531: in function <...vimPackages/start/gitsigns.nvim/lua/gitsigns/manager.lua:493>
stack traceback:
        [C]: in function 'error'
        ...eovimPackages/start/gitsigns.nvim/lua/gitsigns/async.lua:105: in function 'cb'
        ...eovimPackages/start/gitsigns.nvim/lua/gitsigns/async.lua:140: in function 'cb'
        ...vimPackages/start/gitsigns.nvim/lua/gitsigns/manager.lua:48: in function <...vimPackages/start/gitsigns.nvim/lua/gitsigns/manager.lua:46>
```
I'm running the `gitsigns` I got from nixpkgs, from May 19th (I should probably update): https://github.com/lewis6991/gitsigns.nvim/commit/c18b7ca0b5b50596722f3a1572eb9b8eb520c0f1

**Comment by lewis6991** [comment]
Is this still an issue? I am yet to encounter this.

**Comment by scallaway** [comment]
I've been using gitsigns again for about a month or so and haven't encountered the issue again.

My flow otherwise is still the same (writing in Python, with `lazygit` doing stuff in the background). So not sure whether there have been updates to this since I initially created the issue that inadvertently fixed the problem.

I'll keep an eye out for it, but as far as I can tell - right now the problem doesn't exist anymore

**Comment by lewis6991** [comment]
Ok, I'll close the issue.

Please comment if it happens again.

**Comment by xiantang** [comment]
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this message: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:173: Invalid hunk with untracked=true hunk="@@ -172,1 +171 @@"
stack traceback:
        [C]: in function 'assert'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:173: in function 'calc_signs'
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:54: in function 'apply_win_signs0'
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:78: in function 'apply_win_signs'
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:520: in function 'fn'
        .../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/debounce.lua:68: in function 'update'
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua:97: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua:65>
stack traceback:
        [C]: in function 'error'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'cb'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:127: in function 'cb'
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:456: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:441>
"/Users/bytedance/Project/galaxy/infra/dependency/xflow/xflow.go" 823L, 27727B written
I encounter this issue when I want to git checkout to other branch.

gitsign commit: 70584ff

**Comment by xiantang** [comment]
> Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this message: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:173: Invalid hunk with untracked=true hunk="@@ -172,1 +171 @@" stack traceback: [C]: in function 'assert' ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:173: in function 'calc_signs' ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:54: in function 'apply_win_signs0' ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:78: in function 'apply_win_signs' ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:520: in function 'fn' .../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/debounce.lua:68: in function 'update' ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua:97: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua:65> stack traceback: [C]: in function 'error' ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'cb' ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:127: in function 'cb' ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:456: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:441> "/Users/bytedance/Project/galaxy/infra/dependency/xflow/xflow.go" 823L, 27727B written I encounter this issue when I want to git checkout to other branch by fugitive
> 
> gitsign commit: [70584ff](https://github.com/lewis6991/gitsigns.nvim/commit/70584ff9aae8078b64430c574079d79620b8f06d)

**Comment by xiantang** [comment]
could u reopen this issue?

**Comment by lewis6991** [comment]
Can you provide more information on how to reproduce. Error messages only get you so far.

**Comment by xiantang** [comment]
it happens occasionally, i will move to https://github.com/airblade/vim-gitgutter first, thank you!

**Comment by emmanueltouzery** [comment]
it's happening to me at least when staging files. I'm staging files with diffview.nvim and this will occasionally blow up. However unstaging back the file and staging it again does not reproduce the issue.
This happened to me right now with fa052c20aa7cc62ce6a328c7f3bd556c93b5370e.

I think it's a race condition with the git repo changing from underneath gitsigns, with a file being staged..

**Comment by emmanueltouzery** [comment]
Since I'm reproducing this from time to time, I could add a print() before the assert with a if inverting the assert condition, and I could print anything. I currently added one printing the whole hunk, not just the first line. If there's something that I could print out that could help you, let me know.

**Comment by lewis6991** [comment]
So the gitsigns code in the stack trace should only be triggered by a `uv.new_fs_event` callback. And for some reason, diffview is included in the trace. I have no idea why this could happen.

**Comment by emmanueltouzery** [comment]
I got it again. because previously I was afraid that I may have pasted two stacks from two different errors that would have happened in succession, I'll now paste the screenshot of exactly what's appearing on screen
![image](https://github.com/lewis6991/gitsigns.nvim/assets/339433/4c7c13e8-a0a8-455d-9a0e-4f6925df9d69)

**Comment by lewis6991** [comment]
Ok that looks more normal. And is probably some race condition. The `.git` watcher is debounced but for some reason that's not avoiding this problem.

**Comment by emmanueltouzery** [comment]
Right now my computer was under a bit of load. diffview can also sometimes get really quite slow. I think something is keeping the neovim event loop busy, not sure what. Maybe communication with the LSP. So yes, it could be something like that. I'll search for the constant and try increasing it.

**Comment by lewis6991** [comment]
@emmanueltouzery can you try #1008 . Hopefully that should fix it.

**Comment by emmanueltouzery** [comment]
great! I updated to that version and i'll report if i still get the error! :crossed_fingers:

**Comment by lewis6991** [comment]
There could definitely be contention, especially if you have lots of buffers open. I've added `--no-optional-locks` to #1008 just in case it helps things.

To avoid the bug, I believe Gitsigns needs to be able to run these two commands without any interference from other plugins:

```bash
# This tells us the object name of the tracked version of `<path>`. We use this to determine whether the file is tracked or not.
git ... ls-files --stage --others --exclude-standard --eol <path>
# This gets us the contents of tracked version of <path> in the index.
git ... --git-dir <gitdir> show :0:<path>
```

If anything interferes with that, then that error can appear, since the information from each command won't be in sync.

**Comment by emmanueltouzery** [comment]
i think the no-optional-locks help. it feels less sluggish. but it's had to judge. i'll report if i see the assertion again.

**Comment by emmanueltouzery** [comment]
maybe only interesting for me, but... i now wonder whether i got myself in trouble with git performance due to diffview leaving hidden buffers behind https://github.com/sindrets/diffview.nvim/pull/477

I can't be sure, i'll pay attention in the future. But I do run diffview a lot. It's possible it left behind a bunch of unlisted buffers and that gitsigns attached to them and that that got me in trouble. And I didn't think of checking for unlisted buffers previously. I'll pay attention in the future.

**Comment by lewis6991** [comment]
The only way to know would be to look at the Gitsigns cache.
