### ISSUE TITLE
gitsigns show failed

### ISSUE THREAD

**Issue by yimingwangdell** [lewis6991/gitsigns.nvim#865]
### Description

failed.
![image](https://github.com/lewis6991/gitsigns.nvim/assets/121928908/012c6cc8-bfbb-4948-9fe7-d377097ab46d)

### Neovim version

NVIM v0.10.0-dev-835+gdd09630a2

### Operating system and version

manjaro

### Actual behavior

failed.

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by lewis6991** [comment]
This is already fixed https://github.com/lewis6991/gitsigns.nvim/commit/749267aaa863c30d721c9913699c5d94e0c07dd3

**Comment by yimingwangdell** [comment]
![image](https://github.com/lewis6991/gitsigns.nvim/assets/121928908/dd7450cf-3b28-4743-af25-a9b04bd2f929)
@lewis6991 
issue still existing after upgrade.

**Comment by lewis6991** [comment]
That's a different issue.

**Comment by yimingwangdell** [comment]
@lewis6991 That's right, let me create another ticket to trace.

**Comment by lewis6991** [comment]
No, I'll fix it quickly. However what you're trying to do won't work since you need to run `show` on an attached buffer.

**Comment by yimingwangdell** [comment]
@lewis6991 I just want to see commit log for single file, could you tell me which command I should use?

**Comment by lewis6991** [comment]
Can't be done with this plugin.

**Comment by yimingwangdell** [comment]
@lewis6991 could you suggest me a plugin can accomplish this task?

**Comment by lewis6991** [comment]
Maybe https://github.com/sindrets/diffview.nvim or https://github.com/tpope/vim-fugitive

**Comment by yimingwangdell** [comment]
@lewis6991 looks good, thank you!
